name: test
on:
  push:
    branches:
      - "*-tempfix"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - run: composer install --no-progress
      - run: vendor/bin/phpunit --testdox